apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-master
  labels:
    app: os-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-master
  template:
    metadata:
      labels:
        app: os-master
    spec:
      initContainers:
      - name: busybox
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: os-master
        image: opensearchproject/opensearch:1.2.0
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: "opensearch-cluster"
        - name: node.roles
          value: "master"
        - name: cluster.initial_master_nodes
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        - name: plugins.security.disabled
          value: "true"
        ports:
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: os-data
          mountPath: /data
      volumes:
      - name: "os-data" 
        emptyDir:
          medium: ""